Feature/book page
SiMDE-Projects/flairsou-api pull request #112
Opened 2022-02-27 16:13 UTC by tduhautb

Page de présentation générale du livre de compte.

2022-02-28 17:33 UTC, cesar-richard submitted a review, later dismissed

2022-03-09 18:04 UTC, mael-belval requested changes

2022-03-09 18:04 UTC, mael-belval commented on flairsou_frontend/src/components/UI/molecules/AccountList/AccountList.jsx
> +          console.error(`Erreur de suppression du compte ${accountPk}`);
Passer l'erreur via appContext.setAlert() ?

2022-03-09 18:25 UTC, mael-belval commented on flairsou_frontend/src/components/UI/atoms/ConfirmDeleteObject/ConfirmDeleteObject.jsx
> +        />
Sur ce composant, peut-être lui passer plus d'infos sur l'élément à supprimer ? Préciser le nom ou autre, histoire que si on clique sur le bouton suppr de la ligne du dessous, on suppr pas le mauvais élément par erreur

2022-03-09 21:57 UTC, tduhautb commented on flairsou_frontend/src/components/UI/atoms/ConfirmDeleteObject/ConfirmDeleteObject.jsx
> +        />
J'ai ajouté les détails. Pour le bouton annuler, il y en a un dans le popup de confirmation, mais on ne va pas permettre la récupération des éléments supprimés pour l'instant, je pense que ça va demander plus de travail.

2022-03-09 23:06 UTC, mael-belval approved these changes

2022-03-10 05:50 UTC, merged